[project]
name = "pysnap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.124.2",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.38.0",
    "websockets>=15.0.1",
]
